#pragma once

#include "CommandTable.h"

extern CommandInfo kCommandInfo_LoadShader;
extern CommandInfo kCommandInfo_ApplyFullscreenShader;
extern CommandInfo kCommandInfo_RemoveFullscreenShader;
extern CommandInfo kCommandInfo_SetShaderInt;
extern CommandInfo kCommandInfo_SetShaderFloat;
extern CommandInfo kCommandInfo_SetShaderVector;
extern CommandInfo kCommandInfo_SetShaderTexture;
extern CommandInfo kCommandInfo_IsShaderEnabled;